Road-of-CODEr/stupid-week-2021

2021/01/10/hayoung/README.md
2021/01/17/hayoung/README.md

1. [Leetcode dynamic programming 5문제](https://github.com/I-am-interested-in-Javascript/My-LeetCode-Weekly-Contest/tree/master/Week%2013(DP))
2. [Real app next 구조 파악하기](https://github.com/hayoung0Lee/Real-world-next-app) 이틀이상 하기
- [1월 4일(월) 커밋](https://github.com/hayoung0Lee/Real-world-next-app/commit/0451d2efaa5b3e981877640332fc13c7303f6ca2)
- [1월 5일(화) 커밋](https://github.com/hayoung0Lee/Real-world-next-app/commit/4d840932afc14db45d1e069c5de6f2712539ba4a)
3. [Node express 강의 한번 보기](https://github.com/hayoung0Lee/Node-Express) 
1. 백준 풀기 3문제 이상
2. HTTP 완벽 가이드 1장 웹의 기초 파트에서 02. URI 과 리소스, 03. HTTP 메시지, 04. 커넥션 관리 공부하기
3. Debounce / Throttle / Image Lazy Loading 개념 공부하기

1월 1주차 목표 완료 및 2주차 목표 작성

---

2021/01/10/jjeda/README.md
2021/01/10/jjeda/algorithm/BinarayGap.kt
2021/01/10/jjeda/algorithm/CyclicRotation.kt
2021/01/10/jjeda/algorithm/OddOccurrencesInArray.kt

1. Codility 문제
2. Codility 문제 
3. Codility 문제
1. 데이터베이스 개론 5장
2. 데이터베이스 개론 6장 
3. 데이터베이스 개론 7장

feat(jjeda): 1월 10일 결과

---

2021/01/10/soobing/README.md
2021/01/10/soobing/merge-k-sorted-lists.js
2021/01/10/soobing/remove-duplicate-letter.js

1. leet code 두 문제 
- [중복 문자 제거](https://leetcode.com/problems/remove-duplicate-letters/)
- [k개 정렬 리스트 병합](
https://leetcode.com/problems/merge-k-sorted-lists/)
2. next.js 토이프로젝트 main 페이지 개발
3. ~~hooks 딥다이브~~ -> 못했습니다 ㅠ 찐따같은 한주를 보냈습니다
1. leet code 네 문제 
- https://leetcode.com/problems/design-hashmap/
- https://leetcode.com/problems/jewels-and-stones/
- https://leetcode.com/problems/longest-substring-without-repeating-characters
- https://leetcode.com/problems/top-k-frequent-elements
2. next.js 토이프로젝트 aws 연결
3. hooks 딥다이브

feat(soobing): 1월 첫째주 목표

---

2021/01/10/nook1208/README.md

1. [Rust-os: Chap6: bsp: device_driver: Add bcm module](https://github.com/nook1208/rust-rasp-os/commit/858c59baf4b8b5f2cf805641e91e36b6102f0380)
2. [English: Friends shadowing & Memorize sentences](https://github.com/nook1208/english/commit/7458eff723dc6ed653b794c95401abc91c9a97af)
3. [English: Write diaries](https://github.com/nook1208/english/commit/c5c273651b74dcce0a435ee4076d1751c097f960)
1. Rust-os: Write PL011UartInner struct and impl
2. English: Write diaries
3. Leet-code: Write a small program

feat(nook1208): Jan 2nd plan completed

---

2021/01/10/jh20s/README.md
2021/01/10/jh20s/contest#223/1720.cpp
2021/01/10/jh20s/contest#223/1721.cpp
2021/01/10/jh20s/contest#223/1722.cpp
2021/01/10/jh20s/contest#223/1723.cpp

1. [o] [leetcode conteset 223 1번](https://github.com/jh20s/stupid-week-2021/tree/jh20s/2021/01/10/jh20s/contest%23223)
2. [o] [leetcode conteset 223 2번](https://github.com/jh20s/stupid-week-2021/tree/jh20s/2021/01/10/jh20s/contest%23223)
3. [o] [leetcode conteset 223 3,4번](https://github.com/jh20s/stupid-week-2021/tree/jh20s/2021/01/10/jh20s/contest%23223)
1. leetcode conteset 222  cpp로 풀기
2. leetcode conteset 222 python으로 풀기
3. 이팩티브 자바 item57~60 정리

feat(jh20s): Add 0110 todo and complete

---

2021/01/10/jwonylee/README.md

1. 쉽게 배우는 운영체제 1장 정리
2. 알고리즘 3문제 이상 풀기
3. 파이썬 알고리즘 인터뷰 6장 공부
1. 쉽게 배우는 운영체제 2장 정리
2. 파이썬 알고리즘 인터뷰 7장 정리
3. 객체지향의 사실과 오해 읽기

feat(jwonyLee): ~1/10 목표

---

2021/01/10/woohyeonjo/README.md
2021/01/10/woohyeonjo/iot.cpp
2021/01/10/woohyeonjo/sortedlist2.cpp
2021/01/10/woohyeonjo/tree.cpp

1. Pro를 위한 자료구조 구현 연습문제 - Tree 성능 테스트
2. Pro를 위한 자료구조 구현 연습문제 - SortedList 성능 테스트2
3. Pro 집중 실전 문제 - IoT DB
1/9일 시험은 0.8초가 나왔네요... 이제 제출은 항상 하는 것 같습니다... 조만간 따오겠습니다...
1. Pro 대비 문제풀이
2. Pro 대비 문제풀이
3. Pro 대비 문제풀이

feat(woohyeonjo): Complete 2nd week of Jan

---

2021/01/10/InyoungJ/README.md

feat: next week to do list
✅ minor: [1. 파이썬 코딩의 기술 핵심 내용 정리](https://www.notion.so/def2629d669a4f00ae429c6985d00b09)
✅ minor: [2. MySQL lock test 관련 SR 정리](https://www.notion.so/8-0-Instant-Algorithm-Test-1f669af498024decaae02e82e0695a50)
✅ minor: [3. 강성태 영단어 어원편 단어 암기 복습](https://www.notion.so/week04-1956c95e60fb43eaaa7d0c9846740e64)
1. DBA MySQL 운영기술 2장
2. 웹 페이지 완성(Flask, Javascript 이용)
3. MySQL DDL History, Aurora와 비교, 운영 리스트 정리

feat: next week to do list

---

2021/01/10/kerochuu/Facebook.java
2021/01/10/kerochuu/README.md
2021/01/10/kerochuu/사이클게임.java

1. 2020 연말회고
2. 백준 알고리즘 문제풀이 (bit)
3. 백준 알고리즘 문제풀이 (union-find)

Complete 2nd week of Jan.

---

2021/01/10/juheekimm/README.md

1. 스프링 핵심 원리 - 기본편 1강 수강
2. 스프링 핵심 원리 - 기본편 2강 수강
3. 책 읽는 습관 들이기
1. 스프링 핵심 원리 - 기본편 3강 수강
2. 스프링 핵심 원리 - 기본편 4강 수강
3. terminal 명령어 정리 및 익히기
2021년 첫 커밋이네요!
다들 새해 복 많이 받으세요 😄 😄

feat(juheekimm): Complete 2nd week of Jan

---

2021/01/17/huisam/217_ContainsDuplicate.kt
2021/01/17/huisam/README.md
2021/01/24/huisam/README.md

feat(huisam): 1월 3주차 목표 완료

---

2021/01/17/nook1208/README.md

1. [Rust-os: Write PL011UartInner struct and impl](https://github.com/nook1208/rust-rasp-os/commit/fd4e94fb5ebe25521037180f8fd603aa0c56bd1a)
2. [English: Write diaries](https://github.com/nook1208/english/commit/f0ffea9b9320d788774e9d94bfe9fe86eaa6b027)
3. [Leet-code: Write a small program](https://github.com/nook1208/leet_code/commit/0167535fd3f33aac1249cdc89f083dac1cd54cc1)
1. Rust-os: Write PL011Uart impl
2. English: Friends shadowing & Memorize sentences
3. Leet-code: Write a small program

feat(nook1208): Jan 3rd plan completed

---

2021/01/17/jjeda/README.md

1. 데이터베이스 개론 5장
2. 데이터베이스 개론 6장 
3. 데이터베이스 개론 8장
1.  데이터베이스 개론 9장
2.  데이터베이스 개론 10장
3.  데이터베이스 개론 11장

feat(jjeda): Complete 210117

---

2021/01/17/kerochuu/README.md
2021/01/17/kerochuu/소풍.java
2021/01/17/kerochuu/우주탐사선.java

1. 백준 알고리즘 문제풀이 (floyd-warshall + backTracking)
2. 백준 알고리즘 문제풀이 (backTracking)

feat(kerochuu): Complete 3rd week of Jan.

---

2021/01/17/woohyeonjo/README.md
2021/01/17/woohyeonjo/TableCalculator2.cpp
2021/01/17/woohyeonjo/간담회참석.cpp
2021/01/17/woohyeonjo/단어가등장하는횟수.cpp

1. Pro 대비 문제풀이 - Table Calculator2
2. Pro 대비 문제풀이 - 간담회참석
3. Pro 대비 문제풀이 - 단어가등장하는횟수 
1. 알고리즘 문제풀이
2. 알고리즘 문제풀이
3. 알고리즘 문제풀이

feat(woohyeonjo): Complete 3nd week of Jan

---

2021/01/17/jwonylee/README.md

1. 쉽게 배우는 운영체제 2장 정리
2. 파이썬 알고리즘 인터뷰 7장 정리
3. 객체지향의 사실과 오해 읽기
1. 쉽게 배우는 운영체제 3장 정리
2. leetcode 문제 3문제 풀기
3. Understanding Auto Layout 읽고 정리하기

feat(jwonyLee): ~1/17 목표

---

2021/01/24/woohyeonjo/README.md
2021/01/24/woohyeonjo/closest.cpp
2021/01/24/woohyeonjo/convex.cpp
2021/01/24/woohyeonjo/socialmedia.cpp

1. Pro 대비 문제풀이 - Social Media
2. Pro 대비 문제풀이 - Convex
3. Pro 대비 문제풀이 - Closest
1. Pro 대비 문제풀이 
2. Pro 대비 문제풀이
3. Pro 대비 문제풀이

feat(woohyeonjo): Complete 4nd week of Jan

---

2021/01/24/nook1208/README.md

1. [Rust-os: Write PL011Uart impl](https://github.com/nook1208/rust-rasp-os/commit/6dbe6ab6f85200e0c50d94928866a670c7111947)
2. [English: Friends shadowing & Memorize sentences](https://github.com/nook1208/english/commit/8d1387d5078633f4e2a9f9d331575ddaf240b0f8)
3. [Leet-code: Write a small program](https://github.com/nook1208/leet_code/commit/a3235837da56e8efbc643cc5b75fd57460b96438)
1. Rust-os: Define GPIO registers
2. English: Friends shadowing & Memorize sentences
3. Leet-code: Write a small program

feat(nook1208): Jan 4th plan completed

---

2021/01/24/jwonylee/README.md

1. 쉽게 배우는 운영체제 3장 정리
2. leetcode 문제 3문제 풀기
3. Understanding Auto Layout 읽고 정리하기
1. 쉽게 배우는 운영체제 4장 정리
2. leetcode 5문제 풀기
3. Anatomy of a Constraint 읽고 정리하기

feat(jwonyLee): 1월 4주차 목표 완료

---

2021/01/24/beomjo/README.md
2021/01/24/beomjo/algorithm/BOJ/java/1874.java
2021/01/24/beomjo/algorithm/BOJ/java/9012.java
2021/01/24/beomjo/algorithm/BOJ/java/9093.java
2021/01/24/beomjo/algorithm/BOJ/kotlin/1874.kt
2021/01/24/beomjo/algorithm/BOJ/kotlin/9012.kt
2021/01/24/beomjo/algorithm/BOJ/kotlin/9093.kt
2021/01/24/beomjo/clean_code/chapter3.md
2021/01/24/beomjo/clean_code/chapter4.md
2021/01/31/beomjo/README.md

1. Clean Code 3, 4장 읽기
2. Kotlin Coroutine Flow 공부하기 - [정리](https://github.com/beomjo/android-study/blob/main/summary/coroutine/asynchronous_flow.md)
1. Clean Code 5, 6, 7장 읽기
2. Kotlin Coroutine Codelab(for Android) 따라해보기

feat(beomjo): 1월 4주차 목표 완료, 1월 5주차 목표 작성

---

2021/01/24/jjeda/README.md

1.  데이터베이스 개론 9장
2. 데이터베이스 개론 10장
3. 데이터베이스 개론 11장
1. 데이터베이스 개론 12장
2. 데이터베이스 개론 13장
3. 데이터베이스 개론 전체 정리

feat(jjeda): Complete 0124

---

2021/01/24/c17an/readme.md
2021/01/31/c17an/readme.md

1. [유튜브 영상](https://www.youtube.com/watch?v=XK7T3mY1V-w&t=1758s) 을 활용해서 [블로그 소개 페이지](https://c17an.netlify.app/Setting/) 개선하기
2. [리액트에서 `defaultProps`와 분해 할당의 기본값 차이점 정리하기](https://c17an.netlify.app/blog/React/default-props%EB%8A%94-%EC%9D%B4%EC%A0%9C-%EC%95%88%EB%85%95/article/)
3. [브라우저의 same-origin policy에 대해 조사하기](https://github.com/lets-get-job/tech-interview/tree/master/Javascript/12/c17an)
1. [압축강의 영상](https://www.youtube.com/watch?v=g4g2TlTMXXQ) 보고 뷰 기초 정리하기  
2. DP 문제 3문제 풀기 : [RGB 거리](https://www.acmicpc.net/problem/1149), [LIS](https://www.acmicpc.net/problem/11053), [연속합](https://www.acmicpc.net/problem/1912) 
3. [udacity Website Performance Optimization](https://classroom.udacity.com/courses/ud884) 2강까지 보고 내용 정리하기

feat(c17an): 1월 4주차 목표 완료, 1월 5주차 목표 작성

---

2021/01/24/juheekimm/README.md

1. 스프링 입문 - 코드로 배우는 스프링 부트 1, 2강
2. 스프링 입문 - 코드로 배우는 스프링 부트 3, 4강
3. 스프링 입문 - 코드로 배우는 스프링 부트 5, 6강
1. 스프링 핵심 원리 - 기본편 5강 수강
2. 스프링 핵심 원리 - 기본편 6강 수강
3. 스프링 핵심 원리 - 기본편 7강 수강
김영한님의 스프링 강의를 커리큘럼대로 한번 쭉 들어보려 하는데, 입문편이 있는걸 모르고 기본편부터 들었네요..;;ㅎㅎ
그래서 원래 목표했던 기본편 대신 입문편을 수강했고, 이번주에 원래 목표인 기본편을 마저 수강하려 합니다.
다들 한주동안 고생하셨습니다! :)

feat(juheekimm): Complete 4th week of Jan

---

2021/01/24/kerochuu/README.md
2021/01/24/kerochuu/cubeditor.java
2021/01/24/kerochuu/thinkingHeap.java
2021/01/24/kerochuu/나는야포켓몬마스터.java

1. 백준 알고리즘 문제풀이(hashMap) - [[백준 1620] 나는야 포켓몬 마스터 이다솜](https://blog.naver.com/kerochuu/222217731784)
2. 백준 알고리즘 문제풀이(KMP) - [[백준 1701] Cubeditor](https://blog.naver.com/kerochuu/222218618736)
3. 백준 알고리즘 문제풀이(heap + 구현) - [[백준 15942] Thinking Heap](https://blog.naver.com/kerochuu/222218628800)
1. 백준 알고리즘 문제풀이(KMP)
2. 백준 알고리즘 문제풀이(구현)
3. 백준 알고리즘 문제풀이(graph)

feat(kerochuu): Complete 4th week of Jan.

---

2021/01/17/mingdyuo/데이터베이스 공부/README.md
2021/01/24/mingdyuo/README.md
2021/01/24/mingdyuo/스프링 부트와 AWS로 혼자 구현하는 웹 서비스/README.md

1. [알고리즘 스터디 (2회) 출석 문제](https://github.com/mingdyuo/algorithm/commits/master)
2. 도서(스프링 부트와 AWS로 혼자 구현하는 웹 서비스) 8장까지 완료
3. 몽고디비 인액션 1장 읽기
4. \+ [매일 런닝 / 일기쓰기](https://user-images.githubusercontent.com/41130448/105703135-22c09180-5f50-11eb-8090-59256ed13961.png)
5. \+ [네트워크 정리한 것 복습하기](https://github.com/mingdyuo/lets-study-network)
1. 스프링 프로젝트 : 빌드 툴 및 배포 방식 (gradle, maven, jar, war) 공부 및 정리
2. 면접 스터디 - OS 공부 / 복습
3. 알고리즘 스터디 강의 / 출석 문제 풀기
4. \+ 도서(스프링 부트와 AWS로 혼자 구현하는 웹 서비스)에서 이슈 생긴거 해결하고 마무리

feat(mingdyuo): 01/24 완료

---

2021/01/24/sunivers/README.md

1. [자바스크립트 패턴과 테스트 책 7장 정리](https://github.com/sunivers/javascript-pattern-test/blob/master/2%EB%B6%80_%ED%8C%A8%ED%84%B4%EC%9D%84_%EC%9D%91%EC%9A%A9%ED%95%9C_%EC%BD%94%EB%93%9C_%ED%85%8C%EC%8A%A4%ED%8C%85/07_%EB%B6%80%EB%B6%84_%EC%A0%81%EC%9A%A9_%ED%95%A8%EC%88%98.md)
2. [파이썬 알고리즘 풀기](https://github.com/sunivers/Study__Algorithm/commit/0ea2eacb9ece7f4cfb9183b13a15c48077b54d04)
3. [토이 프로젝트 진행 (서버 띄우면서 겪은 에러들 해결 과정 정리)](https://soobakba.tistory.com/53)
1. 자바스크립트 패턴과 테스트 책 8장 정리
2. 파이썬 알고리즘 풀기
3. 토이 프로젝트 진행

✨ 1월 24일 목표 완료

---

2021/01/17/README.md
2021/01/17/design-hashmap.js
2021/01/17/jewels-and-stones.js
2021/01/17/longest-substring-without-repeating-characters.js
2021/01/17/top-k-frequent-elements.js
2021/01/24/README.md

1. leet code 네 문제
https://leetcode.com/problems/design-hashmap/
https://leetcode.com/problems/jewels-and-stones/
https://leetcode.com/problems/longest-substring-without-repeating-characters
https://leetcode.com/problems/top-k-frequent-elements
2. next.js 토이프로젝트 aws 연결
3. hooks 딥다이브
- https://yeoulcoding.tistory.com/m/149
1. leet code 세 문제
https://leetcode.com/problems/course-schedule/
https://leetcode.com/problems/network-delay-time/
https://leetcode.com/problems/cheapest-flights-within-k-stops/
2. next.js 토이프로젝트 끝내기
3. AMD, CommonJS, UMD 정리

feat(soobing): 1월 둘째주 목표 완료, 1월 셋째주 목표 설정

---

2021/01/31/woohyeonjo/README.md
2021/01/31/woohyeonjo/directory.cpp
2021/01/31/woohyeonjo/productionforecast.cpp
2021/01/31/woohyeonjo/searchconstellation.cpp

1. Pro 대비 문제풀이 - 별자리찾기
2. Pro 대비 문제풀이 - 생산량예측
3. Pro 대비 문제풀이 - directory
1. Pro 대비 문제풀이
2. Pro 대비 문제풀이
3. Pro 대비 문제풀이
빨리 따야하는데 업무가 너무 바쁘네요.. 미치겠음둥 ㅎㅎ

feat(woohyeonjo): Complete 5nd week of Jan

---

2021/01/31/c17an/readme.md
2021/02/07/c17an/readme.md

1. 백준에서 DP 문제 3문제 풀기 [RGB 거리](https://github.com/C17AN/Algorithm/blob/master/DP/1149.py) / [연속합](https://github.com/C17AN/Algorithm/blob/master/DP/1912.py) / [LIS](https://github.com/C17AN/Algorithm/blob/master/DP/11053.py)  
2. Vue 기본 문법 정리하기 [정리](https://www.notion.so/chamming2/Vue-70c061ea54f74449a36eabdf80b28d9c) [간단 투두앱](https://github.com/C17AN/vue-todo)  
3. 웹 최적화 기법 강의 2강 듣고 정리하기 [링크](https://www.notion.so/chamming2/2-Critical-Rendering-Path-e72b0cb1c466497dba36c216a3ff19db)
1. 리액트와 socket.io로 채팅 앱 만들어보기
2. Vuex 기본 사용법 정리하기
3. "웹 성능 최적화 기법" 책 3장 1절 ~ 3장 4절 내용 정리하기

feat(c17an): 1월 5주차 목표 달성, 2월 1주차 목표 작성

---

2021/01/31/kwj1270/README.md
2021/02/07/kwj1270/README.md

1. 백기선님의 스터디할래 Enum 정리 [완료](https://velog.io/@kwj1270/Enum)                     
2. 클린코드 12장 창발성 정리 [완료](https://velog.io/@kwj1270/%EC%B0%BD%EB%B0%9C%EC%84%B1)             
3. SSAFY 월말 평가 만점으로 통과하기 [완료](https://user-images.githubusercontent.com/50267433/106286629-32f6aa80-6289-11eb-9333-978477d6b501.PNG)    
1. 백기선님의 스터디할래 Annotation 정리           
2. SSAFY 알고리즘 스터디 4문제(+a) 모두 풀기               
3. SSAFY CS 스터디 `HTTP와 HTTPS`, `DNS와 DHCP` 정리하기

feat(kwj1270): 1월 5주차 목표 달성, 2월 1주차 목표 작성

---

2021/01/31/jjeda/README.md

1.  데이터베이스 개론 12장
2.  데이터베이스 개론 13장
3.  데이터베이스 정리
[OS? Oh YES](https://book.naver.com/bookdb/book_detail.nhn?bid=7288709)
1. 1장
2. 2장
3. 3장

feat(jjeda): Complete 210131

---

2021/01/31/huisam/README.md
2021/02/07/huisam/README.md

🟢 kotlin in action 7장 [읽기](https://user-images.githubusercontent.com/34855745/106357984-d0ff7900-634c-11eb-88ab-f92fc8f48b7f.png)  
🟢 kotlin in action 8장 [읽기](https://user-images.githubusercontent.com/34855745/106357988-d6f55a00-634c-11eb-864f-71e3effef7d3.png)  
🟢 Kotlin 알고리즘 1문제 [풀이](https://github.com/huisam/JinLearnedList/commit/47519e5f8effa7e8e19d4ad1b1f732a7028efc1c)  
❎ kotlin in action 9장 읽기  
❎ JVM kotlin repo 기여  
❎ Kotlin 알고리즘 1문제 풀이

feat(huisam): 1월 5주차 완료

---

2021/01/31/jwonylee/README.md

1. 쉽게 배우는 운영체제 4장 정리
2. leetcode 5문제 풀기
3. Anatomy of a Constraint 읽고 정리하기
1. 쉽게 배우는 운영체제 5장 정리
2. Contacts 프레임워크 톺아보기 작성
3. 오토레이아웃 정복하기 프로젝트 - Social Media Table 만들기

feat(jwonyLee): 1월 5주차 목표 완료, 2월 1주차 목표 작성

---

2021/01/31/nook1208/README.md

1. [Rust-os: Define GPIO registers](https://github.com/nook1208/rust-rasp-os/commits/master)
2. [English: Anki: Add decks](https://github.com/nook1208/english/commit/f4c5e5134aefc60ed673e808640a824055bf528b)
3. [Leet-code: Write a small program](https://github.com/nook1208/leet_code/commit/bccfa48c51e5093758cc2394ea9f884b85881d27)
1. Rust-os: Write GPIOInner struct & impl
2. English: Listen any video or audio file & Write all sentences
3. Leet-code: Write a small program

Feat(nook1208): Jan 5th plan completed

---

2021/01/31/minhyungPark/README.md
2021/01/31/minhyungPark/hadoop.md

1. Hadoop
2. HDFS
3. MR(Map Reduce)
1. Cloudera/quickstart docker
2. 알고리듬
3. 독서하기

feat: complete 5th week of Jan

---

2021/01/31/sunivers/README.md
2021/01/31/sunivers/toy_project_progress.md

1. [자바스크립트 패턴과 테스트 책 8장 정리](https://github.com/sunivers/javascript-pattern-test/blob/master/2%EB%B6%80_%ED%8C%A8%ED%84%B4%EC%9D%84_%EC%9D%91%EC%9A%A9%ED%95%9C_%EC%BD%94%EB%93%9C_%ED%85%8C%EC%8A%A4%ED%8C%85/08_%EB%A9%94%EB%AA%A8%EC%9D%B4%EC%A0%9C%EC%9D%B4%EC%85%98_%ED%8C%A8%ED%84%B4.md)
2. [파이썬 알고리즘 풀기](https://github.com/sunivers/Study__Algorithm/commit/7ce238b2878479fc7c25f96fe68d1dd72a7092d9)
3. 토이 프로젝트 진행
1. 자바스크립트 패턴과 테스트 책 9장 정리
2. 파이썬 알고리즘 풀기
3. 면접 준비

✨ 1월 31일 목표 완료

---

2021/02/07/nook1208/README.md

1. [Rust-os: Write GPIOInner struct & impl](https://github.com/nook1208/rust-rasp-os/commit/1e745e8c4d46f02b52b10eec683679b3e56f7218)
2. [English: Anki: Add some cards to my decks](https://github.com/nook1208/english/commits/main)
3. [English: Listen any video or audio file & Write all sentences](https://github.com/nook1208/english/commits/main)
1. Rust-os: Write Raspberry Pi device driver
2. English: Anki: Add some cards to my decks
3. English: Listen any video or audio file & Write all sentences

feat(nook1208): Feb 1st plan completed

---

2021/02/07/minhyungPark/README.md
2021/02/07/minhyungPark/algorithm/LeetCode1736.kt
2021/02/07/minhyungPark/algorithm/LeetCode1737.kt
2021/02/07/minhyungPark/cloudera.md
2021/02/07/minhyungPark/english.md

1. docker를 이용하여 cloudera 구축해보기
2. 알고리즘
3. 영어공부
1. 실전! 스프링 5를 이용한 리액티브 프로그래밍 5장 읽기
2. 실스리프 6장 읽기
3. 영어공부

2월 1주차 완료 

---

2021/02/07/jwonylee/README.md

1. [쉽게 배우는 운영체제 5장 정리](https://jwonylee.tistory.com/84)
2. [Contacts 프레임워크 톺아보기 작성](https://jwonylee.tistory.com/83)
3. [오토레이아웃 정복하기 프로젝트 - Social Media Table 만들기](https://github.com/jwonyLee/SocialCell/tree/main)
1. 쉽게 배우는 운영체제 6장 정리
2. [토이프로젝트 디테일 화면](https://github.com/jwonyLee/MovieSearchApp/issues/2) 만들기
3. 백준 3문제 풀기(못 풀면 다른 사람 코드 읽고 분석하기)

feat(jwonyLee): 2월 1주차 완료

---

2021/02/07/jjeda/README.md

1. [Os Oh yes 1장](https://github.com/jjeda/Study/blob/master/computer_science/Operating%20System.md#operation-system)
2. [Os Oh yes 2장](https://github.com/jjeda/Study/blob/master/computer_science/Operating%20System.md#interrupt)
3. [Os Oh yes 3장](https://github.com/jjeda/Study/blob/master/computer_science/Operating%20System.md#process-thread)
1. Os Oh yes 4장
2. 5장
3. 6장

feat(jjeda): Complete 210207

---

2021/02/07/juheekimm/README.md

1. [2020년 회고 글쓰기](https://buddev.tistory.com/94)
2. [인프런 JPA 강의 수강](https://user-images.githubusercontent.com/26156701/107155985-06483e80-69bf-11eb-8c13-28d79f023cfe.png)
3. [알고리즘 1문제 이상 풀기](http://boj.kr/b4cbcf92be744b34b3055590689e04b2)
1. 인프런 JPA 강의 수강 - 3강
2. 인프런 JPA 강의 수강 - 4강
3. 알고리즘 1문제 이상 풀기
다들 명절 잘 보내시고 새해 복 많이 받으세요 😄 😄

feat(juheekimm): Complete 1st week of Feb

---

2021/02/07/c17an/readme.md
2021/02/14/c17an/readme.md

1. 리액트와 socket.io를 결합해 채팅 어플리케이션 만들어 보기 - [결과물 저장소 링크](https://github.com/C17AN/react-socket-chat)
2. [vuex 속성 강의](https://www.youtube.com/watch?v=nFh7-HfODYY) 시청 후 내용 정리하기 - [Notion 링크](https://www.notion.so/chamming2/Vuex-324e2e31956d4580bf5b2510badc43a4)
3. [웹 성능 최적화 기법](http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9791186710609&orderClick=LAG&Kc=) 3.1 ~ 3.4 정리하기 - [Notion 링크](https://www.notion.so/chamming2/3-eca6f2b6ca7f4764aac44a86d42edbb1)
1. [WebRTC 요약 영상](https://www.youtube.com/watch?v=FExZvpVvYxA) 보고 내용 정리해보기 
2. [웹 성능 최적화 기법](http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9791186710609&orderClick=LAG&Kc=) 4장 1절 ~ 4장 5절 정리하기
3. [MERN 풀스택 어플리케이션](https://medium.com/swlh/how-to-create-your-first-mern-mongodb-e …

feat(c17an): 2월 1주차 목표 완료 & 2월 2주차 목표 작성

---

2021/02/07/c17an/readme.md
2021/02/14/c17an/readme.md
2021/02/21/c17an/readme.md

1. WebRTC 요약 영상 시청 후 정리 [❗]
- [결과물 노션 링크](https://www.notion.so/chamming2/WebRTC-5b246db07eb5431f8d26eca97318b2c1)
[P.S.] - [ehdrms2034님 블로그](https://velog.io/@ehdrms2034/WebRTC-%EC%9B%B9%EB%B8%8C%EB%9D%BC%EC%9A%B0%EC%A0%80%EB%A1%9C-%ED%99%94%EC%83%81-%EC%B1%84%ED%8C%85%EC%9D%84-%EB%A7%8C%EB%93%A4-%EC%88%98-%EC%9E%88%EB%8B%A4%EA%B3%A0) 를 보고 흥미가 생겨 시작하게 된 공부인데, 배경이론이 꽤나 어려워 깊이있는 정리에는 실패했습니다... 😂
2. 웹 성능 최적화 기법 4장 1절 ~ 4장 5절 정리 [✅]
- [결과물 노션 링크 : 4장 - 이미지 최적화](https://www.notion.so/chamming2/4-50ae46acc80c4eeaa7a2a19c4af7afbe)
3. 튜토리얼을 따라가면서 MERN 스택을 활용한 영화 상영표 어플리케이션 만들어보기 [✅]
- [결과물 및 후기 - 저장소 링크](https://github.com/C17AN/mern-movie)
1. 티스토리 블로그 중 [프로젝트](https://merrily-code.tistory.com/pages/project) 페이지를 캐러셀로 만들기 []
2. 부트스트랩, [json-server](https://github.com/typicode/json-server) 를 활용한 …

feat(c17an) : 2월 2주차 수행 결과 및 2월 3주차 목표 작성

---

2021/02/14/nook1208/README.md

1. [Rust-os: Write Raspberry Pi device driver](https://github.com/nook1208/rust-rasp-os/commits/master)
2. [English: Anki: Add some cards to my decks](https://github.com/nook1208/english/commits/main)
3. [English: Listen any video or audio file & Write all sentences](https://github.com/nook1208/english/commits/main)
1. Rust-os: Use device driver in kernel start function
2. English: Anki: Add some cards to my decks
3. English: Listen any video or audio file & Write all sentences

feat(nook1208): Feb 2nd plan completed

---

2021/02/14/jjeda/README.md

1. OS Oh Yes 4장
2. 5장
3. 6장
1. 7장
2. 8장
3. 9장

feat(jjeda): Complete 2/17

---

2021/02/14/juheekimm/README.md

1. 인프런 JPA 강의 수강 - 3강
2. 인프런 JPA 강의 수강 - 4강
3. 알고리즘 1문제 이상 풀기
1. (조금 늦은) 2021 목표 글쓰기
2. 책 1권 읽기 (개발 말고)
3. 인프런 JPA 강의 수강 - 7, 8강

feat(juheekimm): Complete 2nd week of Feb

---

2021/02/21/jjeda/README.md

1. OS Oh Yes 7장
2. 8장
3. 9장
1. 알고리즘
2. ditto
3. ditto

feat(jjeda): Complete 02.21

---

2021/02/21/nook1208/README.md

1. [Rust-os: Replace QEMU with GPIO & Uart](https://github.com/nook1208/rust-rasp-os/commit/c5fa27c1a1fadb084f27d24026b848c6b2c7fec8)
2. [English: Anki: Add some cards to my decks](https://github.com/nook1208/english/commit/447e7f3ada3ce58a9413f0a6d8ce3d1752eb649f)
3. [English: Listen any video or audio file & Write all sentences](https://github.com/nook1208/english/commit/290487cb20400d6a93dcc83449adde9e0ab719a8)
1. Rust-os: Use device driver in kernel start function
2. English: Anki: Add some cards to my decks
3. English: Anki: Review the webtoon deck

feat(nook1208): Feb 3rd plan completed

---

2021/02/21/jh20s/README.md
2021/02/21/jh20s/contest#228/1758.cpp
2021/02/21/jh20s/contest#228/1759.cpp
2021/02/21/jh20s/contest#228/1760.cpp
2021/02/21/jh20s/contest#228/1761.cpp

1. [o] [leetcode contest 228 cpp로 풀기](https://github.com/jh20s/stupid-week-2021/tree/jh20s/2021/02/21/jh20s/contest%23228)
2. [o] [이팩티브 java 4장 공부](https://blog.naver.com/jh20s/222232051122)
3. [o] [이팩티브 java 4장 블로그 정리](https://blog.naver.com/jh20s/222232051122)
1. leetcode contest 229 cpp로 풀기
2. 이팩티브 java 5장 공부
3. 이팩티브 java 5장 블로그 정리

Add 0221 Complete and Todo

---

2021/02/21/kerochuu/README.md
2021/02/21/kerochuu/wateringTheField.java

1. 백준 알고리즘 문제풀이(kruscal) - [[백준 10021] Watering the Fields](https://blog.naver.com/kerochuu/222250137672)
2. 구름 알고리즘 문제출제
2. 구름 알고리즘 문제출제

feat(kerochuu): Complete 3rd week of Feb.

---

2021/02/21/juheekimm/README.md

1. [(조금 늦은) 2021 목표 글쓰기](https://buddev.tistory.com/95)
2. [책 1권 읽기 (개발 말고) : 괜찮지 않은데 괜찮은 척했다](https://user-images.githubusercontent.com/26156701/108631824-2e4f9b80-74af-11eb-961d-49402867348e.png)
3. [인프런 JPA 강의 수강 - 5, 6강](https://user-images.githubusercontent.com/26156701/108631796-0c561900-74af-11eb-9336-ce1ca1f908cb.png)
1. 인프런 JPA 강의 수강 - 7, 8강
2. 알고리즘 문제 1문제 이상 풀기
3. 스프링 or JPA 강의 내용 조금씩 정리해보기
3,4강 다음에는 5,6강인데.. 실수로 이번주 목표를 7,8강으로 써놨네요.. 😅
이번주도 다들 고생 많으셨습니다!
+PR이 닫혀서 다시 올립니다.

feat(juheekimm): Complete 3rd week of Feb

---

2021/02/28/hayoung/README.md
2021/03/07/hayoung/README.md

1. [백준 풀기 3문제 시간제한 하면서 풀기](https://github.com/I-am-interested-in-Javascript/2021-Algorithm/tree/main/week7)
2. HTTP 완벽 가이드 [Chapter14. 보안 HTTP](https://mytutorials.tistory.com/302), [Chapter15. 엔터티와 인코딩](https://mytutorials.tistory.com/303) 정리하기
3. Node.js 교과서 (4장. http 모듈로 서버 만들기, 5장. 패키지 매니저, 6장. 익스프레스 웹서버 만들기) 까지 공부하기: [해당 커밋까지](https://github.com/hayoung0Lee/NodeJs-textbook/tree/999941cc793f0dec4f656f5e6e212a5d75446c75)
1. [백준 풀기 8문제 시간제한 하면서 풀기](https://github.com/I-am-interested-in-Javascript/2021-Algorithm/tree/main/week8)
2. HTTP 완벽 가이드 [Chapter18. 웹 호스팅](), [Chapter19. 배포 시스템]() 공부하기
3. Node.js 교과서 [9장: 익스프레스로 SNS 서비스 만들기, 10장: 웹 API 서버 만들기까지 공부하기]()

2월 4주차 목표 완료 및 3월 1주차 목표 작성

---

2021/02/28/jjeda/CountingElements.kt
2021/02/28/jjeda/PrefixSums.kt
2021/02/28/jjeda/README.md
2021/02/28/jjeda/TimeComplexity.kt

1. [Codility - Time Complexity](https://app.codility.com/programmers/lessons/3-time_complexity)
2. [Codility - Counting Elements](https://app.codility.com/programmers/lessons/4-counting_elements)
3. [Codility - Prefix Sums](https://app.codility.com/programmers/lessons/5-prefix_sums/)
1. 알고리즘
2. ditto
3. ditto

feat(jjeda): Complete 02.28

---

2021/02/28/nook1208/README.md

1. [Rust-os: Use device driver in kernel start function](https://github.com/nook1208/rust-rasp-os/commit/36d77d7de70d615ba8be4c54e3ff113ca8705f4b)
2. [English: Anki: Add some cards to my decks](https://github.com/nook1208/english/commit/69f38cddf4c23fd99fdb77c07637ce4eb535820d)
3. English: Anki: Review the webtoon deck
1. Rust: Pull Request to 'cargo-bloat' repo
2. English: Read a book

feat(nook1208): Week 4th of Feb Plan Completed

---

2021/02/28/jh20s/README.md
2021/02/28/jh20s/contest#229/1768.cpp
2021/02/28/jh20s/contest#229/1769.cpp
2021/02/28/jh20s/contest#229/1770.cpp
2021/02/28/jh20s/contest#229/1771.cpp

1. [o] [leetcode contest 229 cpp로 풀기](https://github.com/jh20s/stupid-week-2021/tree/jh20s/2021/02/28/jh20s/contest%23229)
2. [o] [이팩티브 java 5장 공부](https://blog.naver.com/jh20s/222260279487)
3. [o] [이팩티브 java 5장 블로그 정리](https://blog.naver.com/jh20s/222260279487)
1. leetcode contest 230 cpp로 풀기
2. 이팩티브 java 6장 공부
3.  이팩티브 java 6장 블로그 정리

feat(jh20s): Add 0228 Complete And ToDo

---

2021/02/28/kerochuu/InfinityMaze.java
2021/02/28/kerochuu/README.md
2021/02/28/kerochuu/crossCountrySkiing.java
2021/02/28/kerochuu/인터넷설치.java

1. [[백준 1800] 인터넷 설치](https://blog.naver.com/kerochuu/222256105290)
2. [[백준 9879] Cross Country Skiing](https://blog.naver.com/kerochuu/222256163737)
3. [[백준 13787] Infinity Maze](https://blog.naver.com/kerochuu/222256305458)
1. 구름 알고리즘 문제출제
2. 구름 알고리즘 문제출제

feat(kerochuu): Complete last week of Feb.

---

2021/02/28/parkinhyo/README.md
2021/03/07/parkinhyo/README.md

1. 파이썬 알고리즘 인터뷰 10장 복습
2. 파이썬 알고리즘 인터뷰 11장 복습
3. 오픽 롤플레이 인강듣기
1. [cccr](https://www.cccr-edu.or.kr/course/course_view.jsp?id=25769) 면접 준비하기
2. 파이썬 알고리즘 인터뷰 복습하기
3. 오픽 롤플레이 마저 듣고 패턴 암기하기

feat(parkinhyo): 2월 4주차 목표 완료.

---

2021/03/07/jjeda/MaximumSliceProblem.kt
2021/03/07/jjeda/README.md
2021/03/07/jjeda/Sorting.kt
2021/03/07/jjeda/StacksAndQueues.kt

1. [Codility - Sorting](https://app.codility.com/programmers/lessons/6-sorting/)
2. [Codility - Stacks And Queues](https://app.codility.com/programmers/lessons/7-stacks_and_queues/)
3. [Codility - Maximum Slice Problem](https://app.codility.com/programmers/lessons/9-maximum_slice_problem/)
[김영한님 HTTP 강의](https://www.inflearn.com/course/http-%EC%9B%B9-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC#)
1. section 1&2
2. section3 
3. section4

feat(jjeda): Complete 03.07

---

2021/03/07/jwonylee/README.md
2021/03/14/jwonylee/README.md

1. 쉽게 배우는 운영체제 9장 ~~정리~~ 읽기
2. 클린코드 2장 정리
3. 초보를 위한 기초 영문법 UNIT 61~120 공부
지금까지 정리한 내용이 책의 내용을 많이 포함하고 있어 저작권 문제가 우려되어 정리에서 읽기로 변경하였습니다. 더불어 기존에 올렸던 글들도 비공개 처리하였습니다. 😂
1. 토이프로젝트 현재까지 구현한 코드 리팩토링 [이슈](https://github.com/jwonyLee/TwitterClone/issues/10)
2. 팀 개발을 위한 Git, GitHub 시작하기 읽고 서평 작성
3. 알고리즘 문제 3문제 풀기

feat(jwonyLee): 3월 1주차 목표 완료, 3월 2주차 목표 작성

---

2021/03/07/jh20s/README.md
2021/03/07/jh20s/contest#230/1773.cpp
2021/03/07/jh20s/contest#230/1774.cpp
2021/03/07/jh20s/contest#230/1775.cpp
2021/03/07/jh20s/contest#230/1776.cpp

1. [o] [leetcode contest 230 cpp로 풀기](https://github.com/jh20s/stupid-week-2021/tree/jh20s/2021/03/07/jh20s/contest%23230)
2. [o] [이팩티브 java 6장 공부](https://blog.naver.com/jh20s/222267858538)
3. [o] [이팩티브 java 6장 블로그 정리](https://blog.naver.com/jh20s/222267858538)
1. leetcode contest 231 cpp로 풀기
2. 인생유니티 교과서 2장 공부
3. 인생유니티 교과서 3장 공부

feat(jh20s): Add 0307 Complete And ToDo

---

2021/03/07/juheekimm/README.md

1. [인프런 JPA 강의 수강 - 9, 10강](https://user-images.githubusercontent.com/26156701/110247478-d1280f80-7faf-11eb-98ee-6f2a189eb888.png)
2. [알고리즘 문제 1문제 이상 풀기](http://boj.kr/f820083b88ca4086964dd4d0fcdc09bc)
3. [책 1권 읽기 - 시시한 사람이면 어때서](https://user-images.githubusercontent.com/26156701/110247844-9a52f900-7fb1-11eb-8992-ff58fc19c418.png)
1. java or spring or JVM 중 주제 정해서 공부하기
2. 알고리즘 문제 1문제 이상 풀기
3. 책 1권 읽기

feat(juheekimm): Complete 1st week of Mar

---

2021/03/07/nook1208/README.md

1. [Rust: Pull Request to 'cargo-bloat' repo](https://github.com/RazrFalcon/cargo-bloat/pull/65)
2. [English: Read a book](https://github.com/nook1208/english/blob/main/book/01-pattern-233/README.md)
3. [Finance: Read a book](https://user-images.githubusercontent.com/50063698/110242455-a03ce000-7f99-11eb-98af-67b0005d3129.png)
1. Rust-os: Booting test
2. English: Read a book

feat(nook1208): Week 1st of Mar Plan Completed

---

2021/03/07/hayoung/README.md
2021/03/14/hayoung/README.md

1. [백준 풀기 8문제 시간제한 하면서 풀기](https://github.com/I-am-interested-in-Javascript/2021-Algorithm/tree/main/week8)
2. HTTP 완벽 가이드 [Chapter18. 웹 호스팅](https://mytutorials.tistory.com/311), [Chapter19. 배포 시스템](https://mytutorials.tistory.com/312) 공부하기
3. Node.js 교과서 [9장: 익스프레스로 SNS 서비스 만들기, 10장: 웹 API 서버 만들기까지 공부하기](https://github.com/hayoung0Lee/socialMedia-React-Express/tree/master/server)
1. [백준 풀기 8문제 시간제한 하면서 풀기](https://github.com/I-am-interested-in-Javascript/2021-Algorithm/tree/main/week9)
2. HTTP 완벽 가이드 [Chapter 20장. 리다이렉션과 부하 균형](), Chapter 21장. 로깅과 사용추적 읽기
3. 코어 자바스크립트 전체 복습: 질문 정리

3월 1주차 목표완료 및 3월 2주차 목표 작성

---

2021/03/14/kerochuu/README.md
2021/03/14/kerochuu/bovineBallet.java
2021/03/14/kerochuu/gridColoring.java
2021/03/14/kerochuu/icyPerimeter.java

1. [[백준 17025] Icy Perimeter](https://blog.naver.com/kerochuu/222275576140)
2. [[백준 15113] Grid Coloring](https://blog.naver.com/kerochuu/222275618488)
3. [[백준 5830] Bovine Ballet](https://blog.naver.com/kerochuu/222275650357)
1. 구름 알고리즘 문제출제
2. 구름 알고리즘 문제출제

feat(kerochuu): Complete 2nd week of Mar.

---

2021/03/14/huisam/README.md

✅ spring5 리액티브 프로그래밍 4장 [읽기](https://user-images.githubusercontent.com/34855745/111038323-a7695f80-846b-11eb-821a-69e2228de1a0.png)  
✅ spring5 리액티브 프로그래밍 5장 [읽기](https://user-images.githubusercontent.com/34855745/111038329-ad5f4080-846b-11eb-9038-59d2dde6c38e.png)  
✅ spring5 리액티브 프로그래밍 6장 [읽기](https://user-images.githubusercontent.com/34855745/111038331-b05a3100-846b-11eb-966c-39792804b544.png)
시간이 없어서 책 읽는 것으로 목표 변경했습니다.
4주간 쉬고 돌아오겠습니다. 당분간은 업로드 하지 않을게요

feat(huisam): 3월 2주차 목표 완료

---

2021/03/14/jjeda/README.md
2021/03/21/jjeda/README.md

[김영한님 HTTP 강의](https://www.inflearn.com/course/http-%EC%9B%B9-%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC#)
1. [section 1&2](https://user-images.githubusercontent.com/51107574/111056021-f8ef0a00-84be-11eb-9512-2720de90b684.png)
2. [section 3](https://user-images.githubusercontent.com/51107574/111056028-0f956100-84bf-11eb-916a-7e8a28b43aea.png)
3. [section 4](https://user-images.githubusercontent.com/51107574/111056039-276ce500-84bf-11eb-9a61-c36d8a128a57.png)
목차만 봤을 때는 다 알고있는 내용이라고 생각이드는데, 실제로 들어보면 새로얻게되는 내용들이 많네요~ HTTP를 처음 접하는 분들이나 내용을 점검하시고 싶은분들에게 추천드립니다!
1. section 5
2. section 6 
3. section 7

feat(jjeda): Complete 03.14

---

2021/03/14/nook1208/README.md

1. [Rust-os: Doc: Armv8: Add some docs](https://github.com/nook1208/rust-rasp-os/commit/1134881cb7267bc7f187e30ea0f9abd629c26fa5) 
2. [English: Read a book and write some scripts](https://github.com/nook1208/english/commits/main)
3. [Finance: Read a book](https://user-images.githubusercontent.com/50063698/111070922-35e6eb00-8517-11eb-90f4-c4127b417d47.png)
1. Rust-os: Doc: Armv8: Add atomic operation doc
2. English: Read a book and write some scripts

feat(nook1208): Week 2nd of Mar Plan Completed

---

2021/03/14/jh20s/README.md
2021/03/14/jh20s/contest#231/1784.cpp
2021/03/14/jh20s/contest#231/1785.cpp
2021/03/14/jh20s/contest#231/1786.cpp
2021/03/14/jh20s/unity/Background.cs
2021/03/14/jh20s/unity/Bullet.cs
2021/03/14/jh20s/unity/DestroyZone.cs
2021/03/14/jh20s/unity/Enemy.cs
2021/03/14/jh20s/unity/EnemyManager.cs
2021/03/14/jh20s/unity/PlayerFire.cs
2021/03/14/jh20s/unity/PlayerMove.cs
2021/03/14/jh20s/unity/ScoreManager.cs

1. [o] [leetcode contest 231 cpp로 풀기](https://github.com/jh20s/stupid-week-2021/tree/jh20s/2021/03/14/jh20s/contest%23231)
2. [o] [인생유니티 교과서 2장 공부](https://github.com/jh20s/stupid-week-2021/tree/jh20s/2021/03/14/jh20s/unity)
3. [o] [인생유니티 교과서 3장 공부](https://github.com/jh20s/stupid-week-2021/tree/jh20s/2021/03/14/jh20s/unity)
1. leetcode contest 232 cpp로 풀기
2. 인생유니티 교과서 3장 복습
3. 인생유니티 교과서 3장 슈팅게임 기능추가 및 다듬기

Add 0314 Complete And ToDo

---

2021/03/14/juheekimm/README.md
2021/03/14/juheekimm/redis.md

1. ~~java or spring or JVM 중 주제 정해서~~ [Redis 공부하기](https://github.com/Road-of-CODEr/stupid-week-2021/blob/126055427bac810b0eb3fd605a6530982b5c5c38/2021/03/14/juheekimm/redis.md)
2. [알고리즘 문제 1문제 이상 풀기](http://boj.kr/1035aff2319e44df8f48a4469a59f60b)
3. [책 읽기 - 자바의 정석](https://user-images.githubusercontent.com/26156701/111078507-1a8cd780-8539-11eb-9d6e-80c8bdb07f84.png)
1. 자바의 정석 1chapter 공부
2. 자바의 정석 1chapter 공부
3. 자바의 정석 1chapter 공부
JVM 공부 하려 했는데.. 업무에 당장 필요해서 계획을 살짝 수정했습니다 😭 
책도 원래는 비개발 서적 읽으려고 했는데 이것도 업무에 당장 필요해서..
업무와 목표가 섞이지 않도록 앞으로 더 노력해 보겠습니다..!

feat(juheekimm): Complete 2nd week of Mar

---

2021/03/21/nook1208/README.md

1. [Rust-os: Doc: Armv8: Add atomic operation doc](https://github.com/nook1208/rust-rasp-os/commit/e81fa64e01789b43fd932163fe783e504d4bac99)
2. [English: Read a book and write some scripts](https://github.com/nook1208/english/commits/main)
3. [Finance: Read a book](https://github.com/nook1208/finance/commit/5adee740ed7e4b5d2f0c1c05752ed6ced550bdb5)
2. English: Read a book and write some scripts

feat(nook1208): Week 3rd of Mar - Plan Completed

---

2021/03/21/beomjo/README.md
2021/03/28/beomjo/README.md

1. MockK 정리 - [정리](https://github.com/beomjo/android-study/blob/main/summary/test/mockk.md)
2. 토이프로젝트 진행 - [진행중](https://user-images.githubusercontent.com/39984656/111906031-06455f00-8a92-11eb-8580-2529c5c29616.png)
3. 알고리즘 문제풀이 3문제 - [풀이1](https://github.com/beomjo/algorithm-study/commit/50e5df0644164843f65b928f04d2b46d1468e9c7), [풀이2](https://github.com/beomjo/algorithm-study/commit/e4e7351efb5ef9f438a76f09dad56eca441ef02d), [풀이3](https://github.com/beomjo/algorithm-study/commit/6b26ce6f92e3b115bc5dff1feea3691d64905959)
1. Android Shared Element Transition 정리
2. 토이프로젝트 진행

feat(beomjo): 3월 3주차 목표 완료, 3월 4주차 목표 작성

---

2021/03/21/kerochuu/README.md
2021/03/21/kerochuu/북서풍2.java
2021/03/21/kerochuu/성곽.java

1. [[백준 2234] 성곽](https://blog.naver.com/kerochuu/222276600430)
2. [[백준 5419] 북서풍](https://blog.naver.com/kerochuu/222283154985)
3. 삼성전자 공채 접수완료
3. 삼성 sw 역량테스트 B형 문제 풀이

feat(kerochuu): Complete 3rd week of Mar.

---

2021/03/28/jjeda/README.md

1. 하이퍼 커넥트 코딩테스트
2. 열혈 TCP/IP chapter 1
3. 열혈 TCP/IP chapter 2
1. 열혈 TCP/IP chapter 3
2. 열혈 TCP/IP chapter 4
3. 열혈 TCP/IP chapter 5

feat(jjeda): Complete 03.28

---

2021/03/28/kerochuu/README.md
2021/03/28/kerochuu/택배.java

- [[백준 8980] 택배](https://blog.naver.com/kerochuu/222290889124)
- 구름 알고리즘 문제출제
- 구름 알고리즘 문제검수
3. 백준 알고리즘 문제풀이

feat(kerochuu): Complete last week of Mar.

---

2021/03/28/nook1208/README.md

1. [Weekly Contest 230](https://github.com/nook1208/leet_code/commit/4985add08922a2bbffce5a0d71cb9d900c4b2798)
2. [English: Write some scripts](https://github.com/nook1208/english/commit/4689e30ce2f771fcef998903e7a931b70bf43ddd)
3. [Finance: Read a book](https://github.com/nook1208/finance/commit/e5c521c0296cdf97451b5751efccda25bdf0504c)
2. English: Write some scripts

feat(nook1208): Week 4th of Mar - Plan Completed

---

2021/03/28/beomjo/README.md
2021/04/04/beomjo/README.md

1. Android Shared Element Transition 정리 - [정리](https://github.com/beomjo/android-study/blob/main/summary/shared_element_transition/overview.md)
2. 토이프로젝트 진행 - [13/21 진행](https://user-images.githubusercontent.com/39984656/112757926-b54fe080-9026-11eb-8311-3c473003a50e.png) 
3. 알고리즘 문제풀이 3문제 - [풀이1](https://github.com/beomjo/algorithm-study/commit/7fec2722436cb810796e84fd9f9f1f8ea00fdec5), [풀이2](https://github.com/beomjo/algorithm-study/commit/8f79695fb177fd8e0ac05aa92af67730ab063908), [풀이3](https://github.com/beomjo/algorithm-study/commit/aa2a97f36edb5813f5800092d64cd90e0c7c4b2e)
1. Android MediaControl Notification 정리
2. 토이프로젝트 진행 

feat(beomjo): 3월 4주차 목표 완료, 4월 1주차 목표 작성

---

2021/04/04/jjeda/README.md

[열혈 TCP/IP - 윤성우](https://book.naver.com/bookdb/book_detail.nhn?bid=6190577)
1. 3장 읽기
2. 4장
3. 5장
1. 6장 읽기 
2. 7장
3. 8장

feat(jjeda): Complete 04.04

---

2021/04/04/jh20s/README.md
2021/04/04/jh20s/contest#232/1790.cpp
2021/04/04/jh20s/contest#232/1791.cpp
2021/04/04/jh20s/contest#232/1792.cpp

1. [o] leetcode contest#232 cpp로 풀기
2. [o] [shootinggame git 정리하기](https://github.com/jh20s/ShootingGame)
3. [o] [shootinggame 마무리](https://github.com/jh20s/ShootingGame)
1. leetcode contest#233 cpp로 풀기
2. shootinggame git 꾸미기
3. shootinggame 블로그 정리

Add 0404 Complete And ToDo

---

2021/04/11/ifmoon/README.md

1. 
2. 
3. 
1. 블로그에 글 1개 쓰기
2. [인강](https://frontendmasters.com/courses/js-fundamentals-functional-v2/) 듣고 정리
3. Leet Code 5문제 풀기

4월 2주차 목표 작성

---

2021/04/04/nook1208/README.md

1. [Write a small program](https://github.com/nook1208/leet_code/commits/master)
2. [English: Write some scripts](https://github.com/nook1208/english/commit/671af4e380bcce3342c2bc100f5b8a8018ebf83c)
2. English: Write some scripts

feat(nook1208): Week 1st of April - Plan Completed

---

2021/04/11/jjeda/README.md

[윤성우의 열혈 TCP/IP 소켓프로그래밍](https://book.naver.com/bookdb/book_detail.nhn?bid=6190577) 읽기
1. 6장
2. 7장
3. 8장
1. 네이버 지원
2. 알고리즘
3. 알고리즘

feat(jjeda): Complete 04.11

---

2021/04/11/nook1208/README.md

1. [Write a small program](https://github.com/nook1208/leet_code/commit/33e8bb9db18683507d02015a337fc4b222797d30)
2. [English: Write some scripts](https://github.com/nook1208/english/commit/671af4e380bcce3342c2bc100f5b8a8018ebf83c)
3. [Finance: Read a book](https://github.com/nook1208/finance/commit/78679f93d88730fb16651ef54e9696cae314770e#diff-3746105765024d122aefed772aafc772b64a9208e67a2a11bb1ac26affbd3bd9)
2. English: Write some scripts

feat(nook1208): Week 2nd of April - Plan Completed

---

2021/04/11/ifmoon/README.md
2021/04/18/ifmoon/README.md

1. 블로그에 글 1개 쓰기
2. 인강 듣고 정리하기 (Objects)
3. LeetCode 5개 풀기
1. 블로그에 글 1개 쓰기
2. 인강 듣고 정리하기 (List Transformations, forEach, map, filter)
3. LeetCode 5개 풀기

feat(ifmoon): 4월 2주차 목표 완료 및 4월 3주차 목표 작성

---

2021/04/11/kerochuu/IQTest.java
2021/04/11/kerochuu/README.md
2021/04/11/kerochuu/마법사상어와화염구.java
2021/04/11/kerochuu/싸지방에간준하.java
2021/04/11/kerochuu/여왕벌.java

- [[백준 20056] 마법사 상어와 파이어볼](https://blog.naver.com/kerochuu/222299875739)
- [[백준 1111] IQ Test](https://blog.naver.com/kerochuu/222306711060)
- [[백준 10836] 인터넷 설치](https://blog.naver.com/kerochuu/222306720517)
- [[백준 12764] 인터넷 설치](https://blog.naver.com/kerochuu/222306725324)
- 백준 알고리즘 문제풀이
- 백준 알고리즘 문제풀이
- 백준 알고리즘 문제풀이

feat(kerochuu): Complete 2nd week of Apr.

---

2021/04/11/jh20s/README.md
2021/04/11/jh20s/contest#233/1800.cpp
2021/04/11/jh20s/contest#233/1801.cpp
2021/04/11/jh20s/contest#233/1802.cpp

1. [o] leetcode contest#232 cpp로 풀기
2. [o] [shootinggame git 꾸미기](https://github.com/jh20s/ShootingGame)
3. [o] [shootinggame 블로그 정리](https://blog.naver.com/jh20s/222306727564)
1.  leetcode contest#233 cpp로 풀기
2.  shootinggame 블로그 정리
3.  게임 프로그래밍 패턴 1~3장

Add 0411 Complete And ToDo

---

2021/04/18/jjeda/README.md
2021/04/18/jjeda/Solution.java
2021/04/18/jjeda/Solution2.java

1. 네이버 공채 지원
2. 알고리즘 문제 풀기
3. 알고리즘 문제 풀기
1. 우아한 테크 캠프 pro 지원
2. 윤성우의 열혈 TCP/IP 9장 읽기
3. 윤성우의 열혈 TCP/IP 10장 읽기

feat(jjeda): Complete 04.18

---

2021/04/18/nook1208/README.md

1. [Write a small program](https://github.com/nook1208/leet_code/commit/97c2167eee687bf2c7ea3efea0aea4fc49fbc2e7)
2. [English: Write some scripts](https://github.com/nook1208/english/commit/31122d46e616c5466be239e32dce7356997d5976)

feat(nook1208): Week 3rd of April - Plan Completed

---

2021/04/18/jwonyLee/README.md

1. 클린 코드 13장 정리
2. 클린 코드 14장 정리
3. 알고리즘 5문제 이상 풀기
한 달 정도 쉬다가 오겠습니다!

feat(jwonyLee): 4월 3주차 목표 완료

---

2021/04/18/huisam/README.md

✅ Jpa [복습](https://user-images.githubusercontent.com/34855745/115147861-04be8500-a098-11eb-8b79-ed52b2be8793.png)  
✅ jvm 레포 kotlin [기여](https://github.com/Road-of-CODEr/we-hate-jvm/pull/58)  
✅ 네이버 영어 회화 [학습](https://learn.dict.naver.com/conversation#/endic/20210216?tabIndex=0)  
1.  데이터 중심 애플리케이션 1장
2. 데이터 중심 애플리케이션 2장 
3. 네이버 영어 회화 공부
잠시 쉬고, 다시 돌아왔습니다 :octocat:

feat(huisam): 4월 3주차 목표 완료

---

2021/04/18/ifmoon/README.md
2021/04/25/ifmoon/README.md

1. 블로그에 글 1개 쓰기
2. [인강](https://frontendmasters.com/courses/js-fundamentals-functional-v2/) .filter()까지 듣고 정리
3. LeetCode 5개 풀기
1. 코틀린 공식 문서 정독하고 정리하기
2. [인강](https://frontendmasters.com/courses/js-fundamentals-functional-v2/) Functions In-Depth까지 듣고 정리
3. LeetCode 5개 풀기

feat(ifmoon): 4월 3주차 목표 완료 및 4월 4주차 목표 작성

---

2021/04/18/beomjo/README.md
2021/04/25/beomjo/README.md

1. Android AAC DataStore 정리 - [정리](https://github.com/beomjo/android-study/blob/main/summary/jetpack/data_store.md)
2. 토이프로젝트 소개 페이지 정리 - [README](https://github.com/beomjo/white-noise-player)
3. 알고리즘 문제풀이 3문제 - [풀이1](https://github.com/beomjo/algorithm-study/commit/9fcec7991ae62779aa25699072a016360ec06760), [풀이2](https://github.com/beomjo/algorithm-study/commit/729f6d50cbbce70f54d37bd6c498299cd4027d6e), [풀이3](https://github.com/beomjo/algorithm-study/commit/19d6c0d2783da2130cd12ed8749cc5b1e70eacaa)
1. Android Jetpack Room 공부
2. Kotlin in Action 1장 읽고 정리

feat(beomjo): 4월 3주차 목표 완료, 4월 4주차 목표 작성

---

2021/04/18/jh20s/README.md
2021/04/18/jh20s/contest#233/1800.cpp
2021/04/18/jh20s/contest#233/1801.cpp
2021/04/18/jh20s/contest#233/1802.cpp

1. [o] leetcode contest#233 cpp로 풀기
2. [o] [shootinggame 블로그 정리](https://github.com/jh20s/ShootingGame)
3. [o] [게임 프로그래밍 패턴 1~3장](https://blog.naver.com/jh20s/222309212946)
1. leetcode contest#237 cpp로 풀기
2. 게임 프로그래밍 패턴 4~5장
3. 게임 프로그래밍 패턴 6~7장

feat(jh20s): 4월 3주차 목표 완료 및 4주차 목표 작성

---

2021/04/18/kerochuu/README.md
2021/04/18/kerochuu/relocation.java
2021/04/18/kerochuu/마법사상어와토네이도.java
2021/04/18/kerochuu/청소년상어2.java

- [[백준 19236] 청소년 상어](https://blog.naver.com/kerochuu/222311476338)
- [[백준 20057] 마법사 상어와 토네이도](https://blog.naver.com/kerochuu/222314807747)
- [[백준 5901] Relocation](https://blog.naver.com/kerochuu/222314910853)
- 백준 알고리즘 문제풀이
- 백준 알고리즘 문제풀이
- 삼성 공채 코딩테스트 응시

feat(kerochuu): Complete 3rd week of Apr.

---

2021/04/18/jiwonKwon/README.md
2021/04/25/jiwonKwon/README.md

1. leetCode 5문제 풀기 (2문제 풀었읍니다..)
2. 클린코드 13장 14장 부록(동시성2) 읽기 (o) 
3. Java8 in Action Chapter3.람다 내용 정리 (x)
1. leetCode 3문제 풀기
2. leetCode 문제 풀이 정리
3. Java8 in Action Chapter3.람다 읽기

feat(jiwonKwon): 4월 3주차 목표 완료 및 4월 4주차 목표 작성

---

2021/04/25/kerochuu/README.md
2021/04/25/kerochuu/게리멘더링2.java
2021/04/25/kerochuu/모노미노도미노3.java
2021/04/25/kerochuu/어른상어.java

- [[백준 19237] 어른 상어](https://blog.naver.com/kerochuu/222317272064)
- [[백준 17779] 게리맨더링2](https://blog.naver.com/kerochuu/222319747502)
- [[프로그래머스] 합승 택시 요금](https://blog.naver.com/kerochuu/222320803229)
- [[프로그래머스] 무지의 먹방 라이브](https://blog.naver.com/kerochuu/222320815412)
- [[백준 20061] Relocation](https://blog.naver.com/kerochuu/222320921373)
- 백준 알고리즘 문제풀이
- 백준 알고리즘 문제풀이
- 구름 알고리즘 문제출제

feat(kerochuu): Complete 4th week of Apr.

---

2021/04/25/jh20s/README.md
2021/04/25/jh20s/contest#238/1837.cpp
2021/04/25/jh20s/contest#238/1838.cpp
2021/04/25/jh20s/contest#238/1839.cpp

1. [o] leetcode contest#238 cpp로 풀기
2. [o] [게임 프로그래밍 패턴 4~5장](https://github.com/jh20s/design-pattern)
3. [o] [게임 프로그래밍 패턴 6~7장](https://blog.naver.com/jh20s/222321635690)
1.  leetcode contest#239 cpp로 풀기
2.  게임 프로그래밍 패턴 7~9장
3.  게임 프로그래밍 패턴 10~12장

feat(jh20s): 0425 Complete And Todo

---

2021/04/25/beomjo/README.md
2021/05/02/beomjo/README.md

1. Android Jetpack Room 공부 - [Room](https://github.com/beomjo/android-study/blob/main/summary/jetpack/room.md)
2. Kotlin in Action 1장 읽고 정리 - [Chapter 1](https://github.com/book-driven-development/kotlin-in-action/blob/main/summary/chapter1.md)
3. 알고리즘 문제풀이 3문제 - [풀이1](https://github.com/beomjo/algorithm-study/commit/36c530c91d5377aaab148b48d8a688f38ed9df5f), [풀이2](https://github.com/beomjo/algorithm-study/commit/3a1a169e826845bbabdc61b02cdc6be4e7e7fa4e), [풀이3](https://github.com/beomjo/algorithm-study/commit/9f186b45e626a1440d6bcf24eb5fef6bb1a67302)
1. Kotlin in Action 2장 읽기
2. Kotlin in Action 3장 읽기

feat(beomjo): 4월 4주차 목표 완료, 5월 1주차 목표 작성

---

2021/04/25/ifmoon/README.md
2021/05/02/ifmoon/README.md

1. 코틀린 공식 문서 정독하고 정리하기
2. [인강](https://frontendmasters.com/courses/js-fundamentals-functional-v2/) 듣기
3. Leetcode 5문제 풀기 
1. 코틀린 공식 문서 정독하고 정리하기
2. [인강](https://frontendmasters.com/courses/js-fundamentals-functional-v2/) 듣기
3. Leetcode 3문제 풀기

4월 4주차 목표 완료 및 5월 1주차 목표 작성

---

2021/04/25/huisam/README.md

✅ 데이터 중심 애플리케이션 [1장](https://user-images.githubusercontent.com/34855745/115997998-34cdd100-a620-11eb-8260-3b5cabda9db9.png)  
✅ 데이터 중심 애플리케이션 [2장](https://user-images.githubusercontent.com/34855745/115998004-3b5c4880-a620-11eb-8c2d-26d4295568e5.png)  
✅ 네이버 영어 회화 [학습](https://learn.dict.naver.com/conversation#/endic/20210424) 
1.  데이터 중심 애플리케이션 3장
2. 데이터 중심 애플리케이션 4장

feat(huisam): 4월 4주차 목표 완료

---

2021/04/25/jjeda/README.md

1. 우아한 테크캠프 pro 자소서 작성
2. 우아한 테크캠프 1주차 과제(진행중)
3. 지그재그 온라인 태스크 완료
1. 우아한 테크캠프 1주차 과제 완료
2. 우아한 테크캠프 2주차 과제 진행
3. TCP/IP 9장, 10장 읽기

feat(jjeda): complete 04.22

---

2021/04/25/nook1208/README.md

1. [Write a small program](https://github.com/nook1208/leet_code/commit/72baa0842d8f2347bbda531ca1db7f60c11678a2)
2. [English: Write a script](https://github.com/nook1208/english/commit/dfa8467aff7009f798db39ae12f19662287be713)
3. [Finance: Read a book](https://github.com/nook1208/finance/commit/606a251777f05a9e642d61f8b0fb50f7d44c58d3)

feat(nook1208): Week 4th of April - Plan Completed

---

2021/05/02/huisam/README.md

✅ 데이터 중심 애플리케이션 [3장](https://user-images.githubusercontent.com/34855745/116787204-def49f80-aadd-11eb-9aa6-c524f5421289.png)  
✅ 데이터 중심 애플리케이션 [4장](https://user-images.githubusercontent.com/34855745/116787206-e4ea8080-aadd-11eb-9c56-57de4194a237.png)  
✅ junit lifecycle 블로그 글 [정리](https://huisam.tistory.com/entry/junit)  
1. 데이터 중심 애플리케이션 5장
2. 데이터 중심 애플리케이션 6장
3. 네이버 영어 회화 보기

feat(huisam): 5월 1주차 목표 완료

---

2021/05/02/jjeda/README.md
2021/05/09/jjeda/README.md

1. 우테캠 프리코스 1주차 완료
2. 우테캠 프리코스 2주차 진행 
3. TCP/IP 9, 10장
1. 우테캠 프리코스 2주차 완료
2. TCP/IP 11장
3. TCP/IP 12장

feat(jjeda): complete 05.02

---

2021/05/02/nook1208/README.md

1. [Write a small program](https://github.com/nook1208/leet_code/commit/35c020fe0dbadef0adee239451bb35780d8c85ad)
2. [English: Write a script](https://github.com/nook1208/english/commit/bf73985d47c56b0d9c13396d78ab34859a7363ec#diff-e8a044136e626f9a002b5d88e88bbb71462ae053d008fbff452c2b6a0c5c7429)
3. [Finance: Read a book](https://github.com/nook1208/finance/commit/5ed750913ab6fae5fa73bb9001404559623140a4#diff-6cd65aa5a20e6db012232eb809e8ac368414323e6ee3a31cced28ba5f2f270a8)

feat(nook1208): Week 1st of May - Plan Completed

---

2021/05/02/kerochuu/README.md
2021/05/02/kerochuu/공.java
2021/05/02/kerochuu/마법사상어와블리자드.java
2021/05/02/kerochuu/마법사상어와비바라기.java
2021/05/02/kerochuu/모노미노도미노3.java
2021/05/02/kerochuu/새로운게임2.java

- [[백준 20061] 모노미노도미노2](https://blog.naver.com/kerochuu/222320921373)
- [[백준 17837] 새로운 게임2](https://blog.naver.com/kerochuu/222324212861)
- [[백준 21611] 마법사 상어와 블리자드](https://blog.naver.com/kerochuu/222328070295)
- [[백준 21610] 마법사 상어와 비바라기](https://blog.naver.com/kerochuu/222330345209)
- [[백준 2695] 공](https://blog.naver.com/kerochuu/222330506596)
- 백준 알고리즘 문제풀이
- 백준 알고리즘 문제풀이
- 구름 알고리즘 문제출제

feat(kerochuu): Complete 1st week of May.

---

2021/05/02/ifmoon/README.md
2021/05/09/ifmoon/README.md

1. 코틀린 공식 문서 정독하고 정리하기
2. [인강](https://frontendmasters.com/courses/js-fundamentals-functional-v2/) 듣기
3. Leet Code 3문제 풀기
1. 코틀린 공식 문서 정독하고 정리하기
2. [인강](https://frontendmasters.com/courses/js-fundamentals-functional-v2/) 듣기
3. Leet Code 3문제 풀기

feat(ifmoon): 5월 1주차 목표 완료, 2주차 목표 작성

---

2021/05/02/beomjo/README.md
2021/05/09/beomjo/README.md

1. Kotlin in Action 2장 읽기 - [Chapter 2](https://github.com/book-driven-development/kotlin-in-action/blob/main/summary/chapter2.md)
2. Kotlin in Action 3장 읽기 - [Chapter 3](https://github.com/book-driven-development/kotlin-in-action/blob/main/summary/chapter3.md)
3. 알고리즘 문제풀이 3문제 - [풀이1](https://github.com/beomjo/algorithm-study/commit/0be5f3e15dbde5858201fef2c30faa9aace2bfb8), [풀이2](https://github.com/beomjo/algorithm-study/commit/41f0f7bd1b4282fb56ea0862d350f213fe9a38c3), [풀이3](https://github.com/beomjo/algorithm-study/commit/cd369bc1780009be5fabeb95627cf1f3032228db)
1. Kotlin in Action 4장 읽기
2. Android ViewPager 2 정리

feat(beomjo): 5월 1주차 목표 완료, 5월 2주차 목표 작성

---

2021/05/09/nook1208/README.md

1. [Write a small program](https://github.com/nook1208/leet_code/commit/671a6f862726c904c6df598314c1986d9ec3aa89)
2. [English: Write a script](https://github.com/nook1208/english/commit/c46982b6e9d3b5610b11efe5201b4d13f98cd6f7)
3. [Finance: Read a book](https://github.com/nook1208/finance/commit/67c6154e07d21666c3cd91e7a9315088f124adaa)

feat(nook1208): Week 2nd of May - Plan Completed

---

2021/05/09/huisam/README.md

✅ 데이터 중심 애플리케이션 [5장](https://user-images.githubusercontent.com/34855745/117574956-afb3e300-b11a-11eb-832f-535fa0a8b729.png)  
✅ 데이터 중심 애플리케이션 [6장](https://user-images.githubusercontent.com/34855745/117574963-b5a9c400-b11a-11eb-9f6e-6eb939f294a7.png)  
✅ 네이버 영어 회화 [학습](https://learn.dict.naver.com/conversation#/endic/20210509)  
1. 데이터 중심 애플리케이션 7장
2. 데이터 중심 애플리케이션 8장 
3.  네이버 영어회화 학습

feat(huisam): 5월 2주차 목표 완료

---

2021/05/09/jh20s/README.md
2021/05/09/jh20s/contest 239/1848.cpp
2021/05/09/jh20s/contest 239/1849.cpp
2021/05/09/jh20s/contest 239/1851.cpp

1. [o] Biweekly Contest 239
2. [o] [BSP 알고리즘 공부]https://blog.naver.com/jh20s/222343029141)
3. [o] [BSP 알고리즘 정리](https://blog.naver.com/jh20s/222343029141)
1. leetcode contest 240 참여
2. 이팩티브 C++ 1장
3. 이팩티브 C++ 2장

feat(jh20s): 0509 Complete And Todo

---

2021/05/02/kerochuu/README.md
2021/05/09/kerochuu/README.md

- ~~백준 알고리즘 문제풀이~~  구름 알고리즘 문제출제
- ~~백준 알고리즘 문제풀이~~  구름 알고리즘 문제출제
- 구름 알고리즘 문제출제
- 백준 알고리즘 문제풀이
- 백준 알고리즘 문제풀이
- 구름 알고리즘 문제출제

feat(kerochuu): Complete 2nd week of May.

---

2021/05/09/beomjo/README.md
2021/05/16/beomjo/README.md

1. Kotlin in Action 4장 읽기 - [Chapter 4](https://github.com/book-driven-development/kotlin-in-action/commit/ead13b040e5caae5f448632bb062288057bec075)
2. Android ViewPager 2 정리 - [정리](https://github.com/beomjo/android-study/commit/2f9327149df9163d98c7f7c53be450a6a045945b)
3. 알고리즘 문제풀이 3문제 - [풀이1](https://github.com/beomjo/algorithm-study/commit/b851fe33febb6705cdfc86c57d2e25cb5f327fac), [풀이2](https://github.com/beomjo/algorithm-study/commit/cf18d550d6ac75b8183f571e24bdce79244420c6), [풀이3](https://github.com/beomjo/algorithm-study/commit/b4192b98088ea7e854a63b179174858f692ecd12)
1. Kotlin in Action 5장 읽기
2. Kotlin in Action 6장 읽기
3. Kotlin in Action 7장 읽기

feat(beomjo): 5월 2주차 목표 완료, 5월 3주차 목표 작성

---

2021/05/09/1ilsang/README.md
2021/05/09/1ilsang/algorithm/leetcode1837.js
2021/05/09/1ilsang/algorithm/leetcode1838.js
2021/05/09/1ilsang/english/naver-en.md
2021/05/09/1ilsang/english/voca.md

1. 알고리즘: LeetCode Weekly Contest 238 도전
2. 영어공부: 네이버영어, 말해보카 도전
3. [블로그 글쓰기](https://blog.naver.com/1ilsang/222345651017)
한달정도 쉬다 오겟습니다...

feat: TODO complete

---

2021/05/16/nook1208/README.md

1. [Write a small program](https://github.com/nook1208/leet_code/commit/b92dfc73de14ce0912427b6061e298fb3976db6e)
2. [English: Write a script](https://github.com/nook1208/english/commit/2f04eafe6f3a0b66e81cf2749042d523ed6f47fa)
3. [Finance: Read a book](https://github.com/nook1208/finance/commit/6fc6e6cb29c532cc658baef86dd39fdc1ec15a7a)
1. Finance: Read a book 1
2. Finance: Read a book 2
3. English: Write a script
다음 주는 신혼여행이라 분량이 좀 적을 것 같네요 :ㅁ

feat(nook1208): Week 3rd of May - Plan Completed

---

2021/05/16/kerochuu/README.md
2021/05/16/kerochuu/Uniqueness.java
2021/05/16/kerochuu/단순2진암호코드.java
2021/05/16/kerochuu/단어세기.java
2021/05/16/kerochuu/바이러스백신.java
2021/05/16/kerochuu/상어초등학교.java
2021/05/16/kerochuu/연속부분합.java
2021/05/16/kerochuu/회전초밥_중.java

- 백준 알고리즘 문제풀이
- swea 알고리즘 문제풀이
- ~~구름 알고리즘 문제출제~~ 정올 알고리즘 문제풀이
→ 최대한 라이브러리를 직접 구현하며 백준, swea, 정올에서 풀이함
- [[ SWEA 1240 ] 단순 2진 암호코드](https://blog.naver.com/kerochuu/222345528013)
- [[ 정올 2612 ] 바이러스 / 백신](https://blog.naver.com/kerochuu/222345592473)
- [[ 정올 xpert ] 책꽂이 만들기](https://blog.naver.com/kerochuu/222348473236)
- [[ 정올 xpert ] 키로거](https://blog.naver.com/kerochuu/222348477785)
- [[ 정올 xpert ] ID검사](https://blog.naver.com/kerochuu/222348485053)
- [[ SWEA 1213 ] String](https://blog.naver.com/kerochuu/222348491789)
- [[ SWEA 1244 ] 최대 상금](https://blog.naver.com/kerochuu/222348499815)
- [[ 백준 5052 ] 전화번호 목록](https://blog.naver.com/kerochuu/222348522627)
- [[ 정올 xpert ] 로봇](https://blog.naver.com/kerochuu/222349781725)
- [[ SWEA 1247 ] 최적 …

feat(kerochuu): Complete 2nd week of May..

---

2021/05/16/jh20s/README.md
2021/05/16/jh20s/contest 240/1854.cpp
2021/05/16/jh20s/contest 240/1855.cpp
2021/05/16/jh20s/contest 240/1856.cpp

1. [o] leetcode contest 240 참여
2. [o] [이팩티브 C++ 1장](https://blog.naver.com/jh20s/222353837214)
3. [o] [이팩티브 C++ 2장](https://blog.naver.com/jh20s/222352298059)
1.  이팩티브 C++ 3장
2.  이팩티브 C++ 4장
3.  이팩티브 C++ 5장

feat(jh20s): 0516 Complete And Todo

---

2021/05/16/beomjo/README.md
2021/05/23/beomjo/README.md

1. Kotlin in Action 5장 읽기 - [정리](https://github.com/book-driven-development/kotlin-in-action/blob/main/summary/chapter5.md)
2. Kotlin in Action 6장 읽기 - [정리](https://github.com/book-driven-development/kotlin-in-action/blob/main/summary/chapter6.md)
3. Kotlin in Action 7장 읽기 - [정리](https://github.com/book-driven-development/kotlin-in-action/blob/main/summary/chapter7.md)
1. Kotlin in Action 8장 읽기
2. Kotlin in Action 9장 읽기
3. Kotlin in Action 10장 읽기

feat(beomjo): 5월 3주차 목표 완료, 5월 4주차 목표 작성

---

2021/05/16/huisam/README.md

✅ 데이터 중심 애플리케이션 [7장](https://user-images.githubusercontent.com/34855745/118495135-dea30800-b75d-11eb-83cd-fb8c47400477.png)  
✅ 데이터 중심 애플리케이션 [8장](https://user-images.githubusercontent.com/34855745/118495153-e4005280-b75d-11eb-9cf0-7b89052f8e6f.png)  
✅ 네이버 영어 회화 [학습](https://learn.dict.naver.com/conversation#/endic/20210516) 
1. 데이터 중심 애플리케이션 9장
2. 데이터 중심 애플리케이션 10장 

feat(huisam): 5월 3주차 목표 완료

---

2021/05/23/nook1208/README.md

1. [English: Write a script](https://github.com/nook1208/english/commit/62225a146116830ef9000f17f5781ab07563bfc5)
2. [Finance: Read a book 1](https://github.com/nook1208/finance/commit/0b0ed9e871bb83acb3f7d5feaa65d1770c625027)
3. [Finance: Read a book 2](https://github.com/nook1208/finance/commit/7686ed88f6b7895f90651c11c1961fac39c30d12)

feat(nook1208): Week 4th of May - Plan Completed

---

2021/05/23/kerochuu/README.md
2021/05/23/kerochuu/떡 먹는 호랑이.java
2021/05/23/kerochuu/색종이(중).java
2021/05/23/kerochuu/암호풀기.java
2021/05/23/kerochuu/하나로.java

- [[ 정올 xpert ] 암호풀기](https://blog.naver.com/kerochuu/222359039566)
- [[ 정올 xpert ] 색종이(중)](https://blog.naver.com/kerochuu/222359044326)
- [[ 정올 xpert ] 떡 먹는 호랑이](https://blog.naver.com/kerochuu/222359050906)
- [[ SWEA 1251 ] 하나로](https://blog.naver.com/kerochuu/222359060458)
- 구름 알고리즘 문제출제
- 백준 알고리즘 문제풀이
- 백준 알고리즘 문제풀이
- 구름 알고리즘 문제출제

feat(kerochuu): Complete 3rd week of May.

---

2021/05/23/jh20s/README.md

1. [o] [이팩티브 C++ 3장](https://blog.naver.com/jh20s/222363330363)
2. [o] [이팩티브 C++ 4장](https://blog.naver.com/jh20s/222363330363)
3. [o] [이팩티브 C++ 5장](https://blog.naver.com/jh20s/222363330363)
1. 이팩티브 C++, modern 이팩티브 C++ 스마트 포인터 부분 블로그 포스팅
2. 이팩티브 C++, modern 이팩티브 C++ 가상함수 부분 블로그 포스팅
3. 릿코드 1회분 풀기

feat(jh20s): 0523 Complete And Todo

---

2021/05/23/beomjo/README.md
2021/05/30/beomjo/README.md

1. Kotlin in Action 8장 읽기 - [정리](https://github.com/book-driven-development/kotlin-in-action/blob/main/summary/chapter8.md)  
2. Kotlin in Action 9장 읽기 - [정리](https://github.com/book-driven-development/kotlin-in-action/blob/main/summary/chapter9.md)  
3. Kotlin in Action 10장 읽기 - [정리](https://github.com/book-driven-development/kotlin-in-action/blob/main/summary/chapter10.md)
1. Kotlin in Action 11장 읽기 
2. Dart Null Safety 정리
3. Android Glide 정리

feat(beomjo): 5월 4주차 목표 완료

---

2021/05/30/nook1208/README.md

1. [Write a small program](https://github.com/nook1208/leet_code/commit/ec0a149d8def4c4d8d5c03ea2079cdde70536f59)
2. [English: Write a script](https://github.com/nook1208/english/commit/44d6c4cfc21611b7bc281e108097f8ced714ff31#diff-41e3633565acd95f5872d154325ed9fb7d5289cd7ecb43eb1e6c810d91aaf4ef)
3. [Finance: Read a book](https://github.com/nook1208/finance/commit/a3b46aa478cee185c006773ec16ce0c072b0375b)

feat(nook1208): Week 5th of May - Plan Completed

---

2021/05/23/huisam/README.md
2021/05/30/huisam/README.md

✅ 데이터 중심 애플리케이션 [11장](https://user-images.githubusercontent.com/34855745/120109416-559bc000-c1a4-11eb-8296-355fbe162c1d.png)  
✅ kotlin 블로그 [포스팅](https://huisam.tistory.com/entry/kotlin-collection)   
✅ 네이버 영어 회화 [학습](https://learn.dict.naver.com/conversation#/endic/20210530)  
1. 데이터 중심 애플리케이션 12장
2. Jpa Id Generation 전략 정리 
저번주꺼를 올렸다 생각했었는데, 아니었네요 ㅠㅠ.. 
이번주에 같이 올려드립니다

feat(huisam): 5월 5주차 목표 완료

---

2021/05/30/kerochuu/README.md
2021/05/30/kerochuu/hacking.java
2021/05/30/kerochuu/달려달려.java

- [[ 백준 3978 ] Hacking](https://blog.naver.com/kerochuu/222368947033)
- [[ 정올 1082 ] 화염에서 탈출](https://blog.naver.com/kerochuu/222370543626)
- [[ 정올 2247 ] 도서관](https://blog.naver.com/kerochuu/222370574501)
- [[ 정올 1761 ] 숫자 야구](https://blog.naver.com/kerochuu/222370595445)
- [[ 백준 1751 ] 달려달려](https://blog.naver.com/kerochuu/222375177205)
- 백준 알고리즘 문제풀이
- 백준 알고리즘 문제풀이
- 구름 알고리즘 문제출제

feat(kerochuu): Complete last week of May.

---

2021/05/30/beomjo/README.md
2021/06/06/beomjo/README.md

1. Kotlin in Action 11장 읽기 - [정리](https://github.com/book-driven-development/kotlin-in-action/blob/main/summary/chapter11.md)
2. Dart Null Safety 정리 - [정리](https://beomseok95.tistory.com/362)
3. Android Glide 정리 - [정리](https://github.com/beomjo/android-study/blob/main/summary/etc/glide.md)
1. Android ViewBinding 공부
2. Android CustomView 정리
3. Dart Null Safety Migration 정리

feat(beomjo): 5월 5주차 목표 완료, 6월 1주차 목표 작성

---

2021/06/06/huisam/README.md

✅ 데이터 중심 애플리케이션 [12장](https://user-images.githubusercontent.com/34855745/121516686-7926fc00-ca29-11eb-8444-5440b1e6d43e.png)  
✅ 데이터 중심 애플리케이션 [1장](https://user-images.githubusercontent.com/34855745/121516731-87751800-ca29-11eb-9e89-65f64c17df8f.png)  
✅ 네이버 영어 회화 [학습](https://learn.dict.naver.com/conversation#/endic/20210606)  
1. 데이터 중심 애플리케이션 2장 읽고 정리할 것 정리
2. 코틀린 spirng batch 정리하기 
3. 네이버 영어 회화

feat(huisam): 6월 1주차 목표 완료

---

2021/06/06/beomjo/README.md
2021/06/13/beomjo/README.md

1. Android ViewBinding 공부 - [정리](https://github.com/beomjo/android-study/blob/main/summary/viewbinding/summary.md)
2. Android CustomView 정리 - [정리](https://github.com/beomjo/android-study/blob/main/summary/customview/summary.md)
3. Dart Null Safety Migration 정리 - [정리](https://beomseok95.tistory.com/363)
1. 토이프로젝트 Dagger Hilt로 마이그레이션
2. Annotation Processor 정리
3. 백준 문제 풀이

feat(beomjo): 6월 1주차 목표 완료, 6월 2주차 목표 작성

---

2021/06/06/jh20s/README.md
2021/06/06/jh20s/contest#238/1880.cpp
2021/06/06/jh20s/contest#238/1881.cpp
2021/06/06/jh20s/contest#238/1882.cpp

1. [o] [팩티브 C++ const 정리](https://blog.naver.com/PostView.nhn?blogId=jh20s&amp;logNo=222387783235)
2. [o] [이팩티브 C++ const 블로그 올리기](https://blog.naver.com/PostView.nhn?blogId=jh20s&amp;logNo=222387783235)
3. 릿코드 1회분 풀기
1. 이팩티브 c++, 모던 이팩티브 C++ cast 관련 정리
2. 이팩티브 c++, 모던 이팩티브 C++ cast 관련 블로그 포스팅
3. 릿코드 1회분 풀기

feat(jh20s): 0606 Complete And Todo

---

2021/06/06/kerochuu/README.md

- 구름 알고리즘 문제출제
- 구름 알고리즘 문제출제
- 구름 알고리즘 문제출제
1.  삼성 sw역량테스트 B형(pro) 기출문제 풀이
2.  삼성 sw역량테스트 B형(pro) 기출문제 풀이
3.  삼성 sw역량테스트 B형(pro) 기출문제 풀이

feat(kerochuu): Complete 1st week of Jun.

---

2021/06/06/nook1208/README.md

1. [Write a small program](https://github.com/nook1208/leet_code/commit/679dbfd97d53f35b25175dd38ec31c8004e3ca03)
2. [English: Write a script](https://github.com/nook1208/english/commit/55b74083d3ca7c071f99b03247ba921f8bbb9ddc)
3. [Finance: Read a book](https://github.com/nook1208/finance/commit/781bea037f759f46e4cec9a7d7052b5c12a1accb)

feat(nook1208): Week 1st of June - Plan Completed

---

2021/06/13/nook1208/README.md

1. [Write a small program](https://github.com/nook1208/leet_code/commit/8d1eaeaebae267e34c68cde6d106d55d2cc878dd)
2. [English: Write a script](https://github.com/nook1208/english/commit/435fe24bedd8eb9c907e92e7e5d17b27e528ee8c)

feat(nook1208): Week 2nd of June - Plan Completed

---

2021/06/13/kerochuu/README.md

- 구름 알고리즘 문제출제
- 구름 알고리즘 문제출제
- 구름 알고리즘 문제출제
- 알고리즘 문제풀이도 했는데 공유가 안돼서 아쉽네요...
1. Pro시험 대비 문제풀이
2. Pro시험 대비 문제풀이
3. Pro시험 대비 문제풀이

feat(kerochuu): Complete 2nd week of Jun.

---

2021/06/13/huisam/README.md

✅ 데이터 중심 애플리케이션 [2장](https://user-images.githubusercontent.com/34855745/122213534-0794f500-cee4-11eb-8fdf-940f6d721634.png)  
✅ spring batch 소개글 [작성](https://huisam.tistory.com/entry/spring-batch-component)  
✅ 네이버 영어 회화 [학습](https://learn.dict.naver.com/conversation#/endic/20210613)  
1. spring batch 더 정리하기
2. 데이터 중심 애플리케이션 3장

feat(huisam): 6월 2주차 목표 완료

---

2021/06/20/nook1208/README.md

1. [Write a small program](https://github.com/nook1208/leet_code/commit/09c6f9a9873dea47a899908f434d55d6611bccec)
2. [English: Write a script](https://github.com/nook1208/english/commit/a240ed2143305bee9584b90c88e851c28bb24135)
2. English: Read a annual report

feat(nook1208): Week 3rd of June - Plan Completed

---

2021/06/20/huisam/README.md

✅ 데이터 중심 애플리케이션 [3장](https://user-images.githubusercontent.com/34855745/122774594-48c24600-d2e4-11eb-886b-60bc00fd9808.png)  
✅ Jpa Datasource 초안 [작성](https://huisam.tistory.com/entry/routingDataSource)  
✅ 네이버 영어 회화 [학습](https://learn.dict.naver.com/conversation#/endic/20210620)  
1. 데이터중심 애플리케이션 4장
2. Datasource 설정 정리 + 테스트코드 

feat(huisam): 6월 3주차 목표 완료

---

2021/06/27/huisam/README.md

✅ vue 프로젝트 [세팅](https://github.com/huisam/kotlin-web/commits/main)  
✅ JVM Repo [기여](https://github.com/Road-of-CODEr/we-hate-jvm/pull/65)    
✅ 네이버 영어 회화 [학습](https://learn.dict.naver.com/conversation#/endic/20210627) 
1. vue 하나씩 해보기
2. 블로그 글 작성 
3. 네이버 영어회화 학습

feat(huisam): 6월 4주차 목표 완료

---

2021/06/20/kerochuu/README.md
2021/06/27/kerochuu/README.md

- 구름 알고리즘 문제출제
- 구름 알고리즘 문제출제
- 구름 알고리즘 문제출제
3. 백준 알고리즘 문제풀이

feat(kerochuu): Complete last week of Jun.

---

2021/07/04/Hwara/readme.md

1. Python GUI modbus RTU Protocol 통신 프로그램 작성
2. Python 코딩 도장 Unit43 ~ 47 완료
3. SQL 첫걸음 1 ~ 5강
첫 PR입니다..!! 열심히 달려보겠습니다 ^0^

feat(Hwara): 7월 1주차 목표 작성

---

2021/06/27/nook1208/README.md

1. [Write a small program](https://github.com/nook1208/leet_code/commit/bb242c7aac11eecb7ef04e455c451e5fd386deff)
2. [English: Have a voice call](https://github.com/nook1208/english/commit/370a8084ca5a015391724538dc865da8b9c26547)
2. English: Have a voice call

feat(nook1208): Week 4th of June - Plan Completed

---

2021/07/04/nook1208/README.md
2021/07/11/nook1208/README.md

1. [Write a small program](https://github.com/nook1208/leet_code/commit/991374cca879613018eb53e69b017d8604a5aa5c)
2. [English: Have a voice call](https://github.com/nook1208/english/commits/main/hellow-talk/README.md)
3. [Finance: Read a book](https://github.com/nook1208/finance/commit/dc263ff9110ec7e339c68f5f567e9bee1dfdca2a#diff-9bde3eb4828bfcc5fbf7aec45a63808b6b0bdbd937de36eaae14a734fd109a8e)
2. English: Have a voice call

feat(nook1208): Week 1st of July - Plan Completed

---

2021/07/04/kerochuu/README.md
2021/07/04/kerochuu/가희와자원놀이.java
2021/07/04/kerochuu/문명.java
2021/07/04/kerochuu/문제추천시스템.java
2021/07/04/kerochuu/문추시2.java
2021/07/04/kerochuu/치삼이의플레이리스트.java
2021/07/04/kerochuu/학부연구생민상.java
2021/07/11/kerochuu/README.md
2021/07/11/kerochuu/cashCow.java
2021/07/11/kerochuu/견우와직녀.java
2021/07/11/kerochuu/두배열의합.java
2021/07/11/kerochuu/미친아두이노.java
2021/07/11/kerochuu/사촌.java
2021/07/11/kerochuu/소코반.java
2021/07/11/kerochuu/스도쿠풀기3.java
2021/07/11/kerochuu/스타트택시.java
2021/07/11/kerochuu/창영이와퇴근.java

- [[백준 14868] 문명](https://blog.naver.com/kerochuu/222414483689)
- [[백준21940] 가운데서 만나기](https://blog.naver.com/kerochuu/222415423038)
- [[백준 21939] 문제 추천 시스템 Version 1](https://blog.naver.com/kerochuu/222415431052)
- [[백준 21939] 학부 연구생 민상](https://blog.naver.com/kerochuu/222415441341)
- [[백준 18131] 치삼이의 플레이리스트](https://blog.naver.com/kerochuu/222415750086)
- [[백준 18128] 치삼이의 징검다리 건너기](https://blog.naver.com/kerochuu/222417843306)
- [[백준 21944] 문제 추천 시스템 Version 2](https://blog.naver.com/kerochuu/222418882374)
- [[백준 21775] 가희와 자원 놀이](https://blog.naver.com/kerochuu/222418914819)
- 백준 알고리즘 문제풀이
- 백준 알고리즘 문제풀이
- 구름 알고리즘 문제출제

(feat)kerochuu: Compele 1st week of July.

---

2021/07/04/huisam/README.md

✅ vue [실습](https://github.com/huisam/kotlin-web/commits/main)  
✅ Mysql master slave 구조 [실습](https://github.com/huisam/mysql-master-slave)    
✅ 네이버 영어 회화 [학습](https://learn.dict.naver.com/conversation#/endic/20210704)
1. vue 실습
2. mysql master slave 계속 해보기 
3. 네이버 영어 회화

feat(huisam): 7월 1주차 목표 완료

---

2021/07/18/kerochuu/README.md
2021/07/18/kerochuu/Rain2.java
2021/07/18/kerochuu/날카로운눈.java
2021/07/18/kerochuu/불켜기2.java
2021/07/18/kerochuu/전단지돌리기.java
2021/07/18/kerochuu/최소비용구하기.java
2021/07/18/kerochuu/해밍경로.java

- [[백준 19542] 전단지 돌리기](https://blog.naver.com/kerochuu/222428899674)
- [[백준 2481] 해밍 경로](https://blog.naver.com/kerochuu/222428984646)
- [[백준 3954] BrainFuck 인터프리터](https://blog.naver.com/kerochuu/222432793677)
- [[백준 1916] 최소비용 구하기](https://blog.naver.com/kerochuu/222432797522)
- [[백준 1637] 날카로운 눈](https://blog.naver.com/kerochuu/222432861899)
- [[백준 14324] Rain](https://blog.naver.com/kerochuu/222436102707)
- [[백준 11967] 불켜기](https://blog.naver.com/kerochuu/222436543282)
- 백준 알고리즘 문제풀이
- 백준 알고리즘 문제풀이
- 백준 알고리즘 문제풀이

feat(kerochuu): Complete 3rd week of July.

---

2021/07/25/kwj1270/README.md
2021/08/01/kwj1270/README.md

1. `DDD Start` 5장 정리 [완료](https://github.com/springframework-sprout/ddd-start/blob/main/05%20%EB%A6%AC%ED%8F%AC%EC%A7%80%ED%86%A0%EB%A6%AC%20%EC%A1%B0%ED%9A%8C%20%EA%B8%B0%EB%8A%A5(JPA%20%EC%A4%91%EC%8B%AC).md)  
2. 백기선님의 스프링 프레임워크 핵심 기술 강의 5개 듣기 [완료](https://user-images.githubusercontent.com/50267433/126907373-4df6e79f-14d5-47a2-829c-97d78d02ff88.png)       
3. 이펙티브 자바 아이템 7개 정리 [완료](https://github.com/springframework-sprout/effective-java/tree/main/03%20%ED%81%B4%EB%9E%98%EC%8A%A4%EC%99%80%20%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4)   
1. `DDD Start` 6장 정리     
2. 이펙티브 자바 아이템 7개 정리    
3. we-hate-jvm 에 AutoConfiguration 내용으로 기여

 feat(kwj1270):7월 4주차 목표 달성 및 8월 1주차 목표 작성 및 

---

2021/11/07/zzisun/README.md

1. 프로젝트 리팩토링하기 
https://github.com/zzisun/GithubApp/issues/10
2. TrOCR 공부하기
3. Realm, Carthage 학습하기
https://github.com/zzisun/SwiftStudy/tree/master/Study/Realm/zzisun/PhoneBookApp
1. 블로그 1일1포스팅하기..!
2. 코테문제 하루에 2️⃣개씩 풀기
3. 프로젝트 2개 리팩토링하기
https://github.com/zzisun/sidedish 
https://github.com/PGHJteam/Project

feat(zzisun): 11월 1주차 목표완료
